version: "3.7"

services:
  ngrok:
    ports:
      - 4040:4040
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - http
      - --domain
      - ${NGROK_SUBDOMAIN}.ngrok.io
      - web:3000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH}

  app:
    environment:
      - APP_URL=${NGROK_SUBDOMAIN}.ngrok.io
